// - LOGIN
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN = 'LOGIN';
export const LOGIN_START = 'LOGIN_START';
//APPLICATION
export const CHANGE_THEME = 'CHANGE_THEME';
export const CHANGE_FONT = 'CHANGE_FONT';
export const FORCE_APPEARANCE = 'FORCE_APPEARANCE';
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const SET_MENU = 'SET_MENU';

export const LOGOUT = 'LOGOUT';
export const REMOVE_USER = 'REMOVE_USER';

//NOTIF
export const NOTIFIKASI_NBADGE = 'NOTIFIKASI_NBADGE';
export const NOTIFIKASI_NBADGE_SUCCESS = 'NOTIFIKASI_NBADGE_SUCCESS';

export const PROJECT_SUCCESS = 'PROJECT_SUCCESS';
export const CART_SUCCESS = 'CART_SUCCESS';

// FOR ACCESS TOKEN
export const REFRESHTOKEN_SUCCESS = 'REFRESHTOKEN_SUCCESS';
export const REFRESHTOKEN_REQUEST = 'REFRESHTOKEN_REQUEST';
export const REFRESHTOKEN_FAILED = 'REFRESHTOKEN_FAILED';
export const UPDATE_REFRESHTOKEN = 'UPDATE_REFRESHTOKEN';

// FOR CART STORE
export const CARTSTORE_REQUEST = 'CARTSTORE_REQUEST';
export const CARTSTORE_SUCCESS = 'CARTSTORE_SUCCESS';
export const CARTSTORE_FAILED = 'CARTSORE_FAILED';

export const UNIT_SUCCESS = 'UNIT_SUCCESS';
export const CHOOSED_UNIT = 'CHOOSED_UNIT';
